import * as theDay from "../src/06.ts";
import { assertEquals } from "@std/assert";

const input = `....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...`;

Deno.test("day 06", () => {
  assertEquals(theDay.run(input), [41, "part2"]);
});
